//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeGocNho_63134417.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CafeGocNho_63134417Entities : DbContext
    {
        public CafeGocNho_63134417Entities()
            : base("name=CafeGocNho_63134417Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN> BAN { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<LOAIMATHANG> LOAIMATHANG { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
    
        public virtual int HoaDon_TimKiem(string mAHD, string mABAN, string nGAYmin, string nGAYmax, string mANV)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            var mABANParameter = mABAN != null ?
                new ObjectParameter("MABAN", mABAN) :
                new ObjectParameter("MABAN", typeof(string));
    
            var nGAYminParameter = nGAYmin != null ?
                new ObjectParameter("NGAYmin", nGAYmin) :
                new ObjectParameter("NGAYmin", typeof(string));
    
            var nGAYmaxParameter = nGAYmax != null ?
                new ObjectParameter("NGAYmax", nGAYmax) :
                new ObjectParameter("NGAYmax", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_TimKiem", mAHDParameter, mABANParameter, nGAYminParameter, nGAYmaxParameter, mANVParameter);
        }
    
        public virtual int Menu_TimKiem(string mAMH, string tENMH, string gIACAmin, string gIACAmax, string dVT, string mALOAI)
        {
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var tENMHParameter = tENMH != null ?
                new ObjectParameter("TENMH", tENMH) :
                new ObjectParameter("TENMH", typeof(string));
    
            var gIACAminParameter = gIACAmin != null ?
                new ObjectParameter("GIACAmin", gIACAmin) :
                new ObjectParameter("GIACAmin", typeof(string));
    
            var gIACAmaxParameter = gIACAmax != null ?
                new ObjectParameter("GIACAmax", gIACAmax) :
                new ObjectParameter("GIACAmax", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var mALOAIParameter = mALOAI != null ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Menu_TimKiem", mAMHParameter, tENMHParameter, gIACAminParameter, gIACAmaxParameter, dVTParameter, mALOAIParameter);
        }
    }
}
