//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeGocNho_63134417.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADON = new HashSet<HOADON>();
            this.HOADON1 = new HashSet<HOADON>();
        }
    
        public string MANV { get; set; }
        public string HONV { get; set; }
        public string TENNV { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<short> CHUCVU { get; set; }
        public Nullable<short> GIOITINH { get; set; }
        public string SDT { get; set; }
        public string CCCD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON1 { get; set; }
    }
}
